title: Mulheres do barro
email: contato.mulheresdobarro@gmail.com
description: >-
  Mapeamento de mulheres artesãs da cidade de Tracunhaém - PE
url: "https://mulheresdobarro.com.br" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mulheresdobarro
github_username:  mulheresdobarro

# Build settings
theme: minima
plugins:
  - jekyll-feed