title: Mulheres do barro
email: contato.mulheresdobarro@gmail.com
description: >-
  Mapeamento de mulheres artesãs da cidade de Tracunhaém - PE
url: "https://mulheresdobarro.com.br"
baseurl: ""
lang: "pt-BR"
timezone: America/Recife
instagram_username: mulheresdobarro
youtube_username: "@mulheresdobarro"

# Build settings
theme: minima
plugins:
  - jekyll-feed